apiVersion: v1
kind: Namespace
metadata:
  name:  elk-test

---

apiVersion: v1
kind: Pod
metadata:
  name: counter
  namespace: elk-test
spec:
  containers:
  - name: count
    image: busybox
    # 輸出hello world
    args: [/bin/sh, -c,
            'i=0; while true; do echo "hello world: $i: $(date)"; i=$((i+1)); sleep 3; done']